server:
  port: 80


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
#yml添加配置,开启 hystrix
feign:
  hystrix:
    enabled: true

logging:
  level:
    #feign日志以什么级别监控哪个接口
    cn.com.yusys.SpringCloud.service.PaymentHystrixService.paymentInfo_OK: debug