server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率介于0到1.1表示全部采集
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/db2020?serverTimezone=GMT%2B8
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
     defaultZone: http://eureka7002.com:7002/eureka #单机版的
     #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7004.com:7004/eureka   # 集群版
  instance:
    # 主机名称修改(配置后Eureka Server处显示,不配置显示默认注册名)
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 访问路径可以显示IP地址
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.yusys.SpringCloud.entities     #所有Entity别名类所在包